### ISSUE TITLE
Add directions?

### ISSUE THREAD

**Issue by amabdallah** [nbengdahl/CRP#1] opened 2018-04-25 20:15 UTC
Could you please add directions to the repo on how to run the Matlab code for a beginner (i.e., copy some of the comments inside the files into the ReadMe here)? 

> users will first need to install the PhreeqcRM library which can be found at: http://wwwbrr.cr.usgs.gov/projects/GWC_coupled/phreeqc/

and how to install the PhreeqcRM library? 
I went to the provided PHREEQC URL site but had no clue what to exactly install. There are many things to install (e.g., GUI, Source code, Batch Versions, etc)

In installed the GUI, Batch version executable but I'm still getting this error in Matlab
 

>  Error using loadlibrary
> Could not find file RM_interface_C.h.
> 
> Error in loadlibrary
> 
> Error in RxnChain (line 70)
>     loadlibrary('libphreeqcrm','RM_interface_C.h');

I googled how to install this libphreeqcrm for Matlab but with no luck.

I was just trying to reproduce the figures in the paper as part of a reproducibilit study.

**Comment by nbengdahl** [comment] 2018-04-26 01:16
Please note that the provided link directs you to a list of codes available for download but only one is PhreeqcRM; any download that does not begin with "phreeqcrm" is not the required component library (for example, "iphreeqc-3.4.0-12927.tar.gz" is not correct). Installation instructions for the component library are provided through the "PhreeqcRM readme" link near the top of the page and installation questions for PhreeqcRM should be directed to its developers.

**Comment by amabdallah** [comment] 2018-05-28 16:51
Well, I think this repo ReadMe file could help users further if there are more specific details like you just mentioned. For example, give the direct URL to the ReadMe of the phreeqcrm
ftp://brrftp.cr.usgs.gov/pub/charlton/phreeqcrm/README.PhreeqcRM.12927.TXT
Even such ReadME is very elaborate, maybe summarize the key steps that get a beginner to get started with it. 
Another way to help the user directly get to download what is needed, is to provide this snapshot in this repos ReadME and tell the user to download one of these. phreeqc, phreeqci, phreeqcrm, IPhreeqcCOM are too many to really get it from the first time.
![image](https://user-images.githubusercontent.com/3268971/40623393-0a4b414a-6264-11e8-880d-38c854787902.png)

We found that unclear directions are a big reason why documented studies fail the reproducibility test. Yes if a user spends a day, they might be able to figure it out, but that's too long. Not all users really know phreeq. Imagine a fresh masters or PhD student. It will be frustrating to struggle to get a well-documented code going. The more the instructions think of the user as a dummy to the code, the better they are. 

Good luck
Adel

**Comment by nbengdahl** [comment] 2018-05-28 17:21
Your suggestion is appreciated but please remember that this is clearly stated as an example code strictly for research purposes and **it is not an out-of-the-box, standalone modeling package** as some other codes may be that require less experience with setting up required components. Users of any research code should familiarize themselves with every aspect of the code before attempting to use it. This includes all supporting codes and libraries, and educational level or career stage does not excuse one from this responsibility, which may take some longer than others. 

Many users have successfully installed the code and have reported successful reproduction of the examples with no problems. Since this is not an issue with the CRP code I am closing the issue.

**Closed as completed by nbengdahl** 2018-05-28 17:21 UTC
